apiVersion: v1
kind: ConfigMap
metadata:
  name: sbms-notification-db-config
  namespace: sbms
data:
  DB_URL: "jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/sbms_notification_db"
  RABBITMQ_HOST: "rabbitmq"
<<<<<<< HEAD
  RABBITMQ_PORT: "5672"
=======
  RABBITMQ_PORT: "5670"
>>>>>>> 4da8dc71f9c94208e394fa31d877947edeba6c79
